version: 2.1

jobs:
  setup_dependencies:
    docker:
      - image: cryptiumlabs/juvix-ci
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - juvix-cache-v2-{{ checksum "package.yaml" }}
      - run:
          name: Build dependencies
          command: stack build -j2 --only-dependencies +RTS -N2 -qg
          no_output_timeout: 1200
      - run:
          name: Build Juvix
          command: stack build --copy-bins --fast
      - persist_to_workspace:
          root: /root
          paths:
            - .
      - save_cache:
          name: Cache dependencies
          key: juvix-cache-v2-{{ checksum "package.yaml" }}
          paths:
            - "~/.stack"
            - ".stack-work"

  test_suite:
    docker:
      - image: cryptiumlabs/juvix-ci
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Run tests
          command: stack test --fast --test-arguments "--hide-successes --ansi-tricks false"
          no_output_timeout: 1200

workflows:
  version: 2.1
  test-suite:
    jobs:
      - setup_dependencies
      - test_suite:
          requires:
            - setup_dependencies
